#########################################################################################
#                                                                                       #
commands:
#check of player is running or not(in tick)
  updateStamina:
    value: 10
    description: "check of player is running or not(in tick)"
  #general stamina
  startStamina:
    value: 50
    description: ""

  #max stamina
  maxStamina:
    value: 150
    description: ""

  #increase amount when stamina update
  staminaDecreaseAmount:
    value: 2.0
    description: ""

  #decrease amount when stamina update
  staminaIncreaseAmount:
    value: 4.0
    description: ""

  #maxStaminaDecreaseAmount
  maxStaminaDecreaseAmount:
    value: 0.01
    description: ""

  #give you slowness under this number
  slownessStamina:
    value: 25
    description: ""

#mode that allow stamina
staminaInMode:
  - SURVIVAL
  #- CREATIVE
  #- ADVENTURE
  #- SPECTATOR

titleFormat: "&6&lStamina&r [{stamina}/{startStamina}]"
