name: Stamina
version: ${project.version}
main: org.apache.maven.stamina.Stamina
api-version: 1.13
commands:
  stamina:
    description: Reload/save The Stamina Plugin
  setvalue:
    description: Set a config value via command